version: '3'
services:
    lsyncd:
        image: abataloff/lsyncd:latest
        build: .
        restart: always
        container_name: lsyncd
        volumes:
            - ./lsyncd:/lsyncd
            - ./data:/data
            - ./keys:/root/.ssh